<!DOCTYPE html>
<html class="zurmo" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport"  content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="apple-touch-icon" sizes="144x144" href="/zurmo/app/themes/default/images/touch-icon-iphone4.png" />
        <style>@font-face{font-family: 'zurmo_gamification_symbly_rRg';src: url('<?php echo $this->basePath();?>/public/fonts/zurmogamificationsymblyregular-regular-webfont.eot');src: url('<?php echo $this->basePath();?>/public/fonts/zurmogamificationsymblyregular-regular-webfont.eot?#iefix') format('embedded-opentype'), url('<?php echo $this->basePath();?>/public/fonts/zurmogamificationsymblyregular-regular-webfont.woff') format('woff'), url('<?php echo $this->basePath();?>/public/fonts/zurmogamificationsymblyregular-regular-webfont.ttf') format('truetype'), url('<?php echo $this->basePath();?>/public/fonts/zurmogamificationsymblyregular-regular-webfont.svg#zurmo_gamification_symbly_rRg') format('svg');font-weight: normal;font-style: normal;unicode-range: U+00-FFFF;}</style>
        <link rel="shortcut icon" href="/zurmo/app/themes/default/ico/favicon.ico" />
        <link rel="stylesheet" type="text/css" href=" <?php echo $this->basePath();?>/default/css/style.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/default/css/keyframes.css" />
        <script type="text/javascript" src="<?php echo $this->basePath();?>/default/js/zuzu.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath();?>/default/js/ZurmoDialog.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath();?>/default/js/mobile-interactions.js"></script>
        <script type="text/javascript">
            var desktopNotifications =
                {
                notify:function(image, title, body)
                {
                    
                    return false;
                },
                isSupported:function()
                {
                    if (typeof window.webkitNotifications != 'undefined')
                    {
                        return true
                    }
                    else
                    {
                        return false
                    }
                },
                requestAutorization:function()
                {
                    if (typeof window.webkitNotifications != 'undefined')
                    {
                        if (window.webkitNotifications.checkPermission() == 1)
                        {
                            window.webkitNotifications.requestPermission();
                        }
                        else if (window.webkitNotifications.checkPermission() == 2)
                        {
                            alert('You have blocked desktop notifications for this browser.');
                        }
                        else
                        {
                            alert('You have already activated desktop notifications for Chrome');
                        }
                    }
                    else
                    {
                        alert('This is only available in Chrome.');
                    }
                }
            };
            
            $(document).ready(function()
            {
                $('#FlashMessageBar').jnotifyInizialize(
                {
                    oneAtTime: false,
                    appendType: 'append'
                }
            );
            }
        );
        </script>
        <title>ZurmoCRM - Products</title>
    </head>
    <body class="blue">
        <div id="ProductsPageView" class="ZurmoDefaultPageView ZurmoPageView PageView">
            <div id="ZurmoDefaultView">
                <div class="GridView">
                    <div id="HeaderView">                        
						<div id="MainLogo" class="zurmo-logo"></div>
                        <div class="GridView">
                            <div id="HeaderLinksView">
                                <div class="clearfix">
                                    <a href="#" id="nav-trigger" title="Toggle Navigation">&rsaquo;</a>
                                    <div id="corp-logo">
                                        <a href="/zurmo/app/index.php/home/default">
                                            <img src="/zurmo/app/themes/default/images/Zurmo_logo.png" alt="Zurmo Logo" height="32" width="107" />
                                        </a>
                                        <span>Demo Company Inc.</span>
                                    </div>
                                    <div id="user-toolbar" class="clearfix">
                                        <div id="header-game-dashboard-link-wrapper" class="user-menu-item">
                                            <a id="header-game-dashboard-link" href="#">?</a>
                                        </div>
                                        <ul id="user-header-menu" class="user-menu-item nav">
                                            <li class="parent last">
                                                <a href="javascript:void(0);">
                                                    <span>super</span>
                                                </a>
                                                <ul>
                                                    <li>
                                                        <a href="/zurmo/app/index.php/users/default/profile">
                                                            <span>My Profile</span>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="/zurmo/app/index.php/gamification/default/leaderboard">
                                                            <span>Leaderboard</span>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="/zurmo/app/index.php/emailMessages/default/matchingList">
                                                            <span>Data Cleanup</span>
                                                        </a>
                                                    </li>
                                                    <li class="last">
                                                        <a href="/zurmo/app/index.php/zurmo/default/logout">
                                                            <span>Sign out</span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                        <ul id="settings-header-menu" class="user-menu-item nav">
                                            <li class="parent last">
                                                <a href="javascript:void(0);">
                                                    <span>Administration</span>
                                                </a>
                                                <ul>
                                                    <li>
                                                        <a href="/zurmo/app/index.php/configuration">
                                                            <span>Administration</span>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="/zurmo/app/index.php/designer/default">
                                                            <span>Designer</span>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="/zurmo/app/index.php/import/default">
                                                            <span>Import</span>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="/zurmo/app/index.php/users/default">
                                                            <span>Users</span>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="http://www.zurmo.com/needSupport.php">
                                                            <span>Need Support?</span>
                                                        </a>
                                                    </li>
                                                    <li class="last">
                                                        <a href="/zurmo/app/index.php/zurmo/default/about">
                                                            <span>About Zurmo</span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="GridView">
                                <div id="GlobalSearchAndShortcutsCreateMenuView">
                                    <div id="app-search" class="clearfix">
                                        <select class="ignore-style" id="globalSearchScope" multiple="multiple" style="display:none;" size="4" name="globalSearchScope[]">
                                            <option value="All" selected="selected">All</option>
                                            <option value="accounts">Accounts</option>
                                            <option value="contacts">Contacts</option>
                                            <option value="leads">Leads</option>
                                            <option value="opportunities">Opportunities</option>
                                        </select>
                                        <input class="global-search global-search-hint" onfocus="$(this).removeClass(&quot;global-search-hint&quot;); $(this).val(&quot;&quot;);" onblur="$(this).val(&quot;&quot;)" id="globalSearchInput" type="text" value="Search by name, phone, or e-mail" name="globalSearchInput" />
                                        <span class="z-spinner"></span>
                                    </div>
                                    <ul id="ShortcutsMenu" class="nav">
                                        <li class="parent last">
                                            <a href="javascript:void(0);">
                                                <span>Create</span>
                                            </a>
                                            <ul>
                                                <li id="home"><a href="/zurmobajakan/public/application/index/index"><span></span><em></em><span>Home</span></a></li>
<li id="mashableInbox"><a href="/zurmobajakan/public/inbox/inbox/index"><span></span><em></em><span>Inbox<span class="unread-inbox-count">1</span></span></a></li>
<li id="accounts"><a href="/zurmobajakan/public/account/account/index"><span></span><em></em><span>Accounts</span></a></li>
<li id="leads"><a href="/zurmobajakan/public/leads/leads/index"><span></span><em></em><span>Leads</span></a></li>
<li id="contacts"><a href="/zurmobajakan/public/contact/contact/index"><span></span><em></em><span>Contacts</span></a></li>
<li id="opportunities"><a href="/zurmobajakan/public/opportunity/opportunity/index"><span></span><em></em><span>Opportunities</span></a></li>
<li id="marketing" class="hidden-nav-item"><a href="/zurmobajakan/public/marketing/marketing/index"><span></span><em></em><span>Marketing</span></a></li>
<li id="projects" class="hidden-nav-item"><a href="/zurmobajakan/public/project/project/index"><span></span><em></em><span>Projects</span></a></li>
<li id="products" class="active"><a href="/zurmobajakan/public/product/"><span></span><em></em><span>Products</span></a></li>
<li id="reports" class="hidden-nav-item last"><a href="/zurmobajakan/public/report/report/index"><span></span><em></em><span>Reports</span></a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
						 </div>
                    <div class="AppContainer clearfix GridView">
                        <div class="AppNavigation clearfix GridView">
                            <div id="MenuView">
                                <ul class="nav">
                                    <li id="home">
                                        <a href="<?php echo $this->basePath();?>">
                                            <span></span>
                                            <em></em>
                                            <span>Home</span>
                                        </a>
                                    </li>
                                    <li id="mashableInbox">
                                        <a href="<?php echo $this->basePath();?>/inbox">
                                            <span></span>
                                            <em></em>
                                            <span>Inbox
                                                <span class="unread-inbox-count">8</span>
                                            </span>
                                        </a>
                                    </li>
                                    <li id="accounts">
                                        <a href="<?php echo $this->basePath();?>/accounts">
                                            <span></span>
                                            <em></em>
                                            <span>Accounts</span>
                                        </a>
                                    </li>
                                    <li id="leads">
                                        <a href="<?php echo $this->basePath();?>/leads">
                                            <span></span>
                                            <em></em>
                                            <span>Leads</span>
                                        </a>
                                    </li>
                                    <li id="contacts">
                                        <a href="<?php echo $this->basePath();?>/contacts">
                                            <span></span>
                                            <em></em>
                                            <span>Contacts</span>
                                        </a>
                                    </li>
                                    <li id="opportunities">
                                        <a href="<?php echo $this->basePath();?>/opportunity">
                                            <span></span>
                                            <em></em>
                                            <span>Opportunities</span>
                                        </a>
                                    </li>
                                    <li id="marketing" class="hidden-nav-item">
                                        <a href="<?php echo $this->basePath();?>/marketing">
                                            <span></span>
                                            <em></em>
                                            <span>Marketing</span>
                                        </a>
                                    </li>
                                    <li id="projects" class="hidden-nav-item">
                                        <a href="<?php echo $this->basePath();?>/projects">
                                            <span></span>
                                            <em></em>
                                            <span>Projects</span>
                                        </a>
                                    </li>
                                    <li id="products" class="active">
                                        <a href="<?php echo $this->basePath();?>/product">
                                            <span></span>
                                            <em></em>
                                            <span>Products</span>
                                        </a>
                                    </li>
                                    <li id="reports" class="hidden-nav-item last">
                                        <a href="<?php echo $this->basePath();?>/report">
                                            <span></span>
                                            <em></em>
                                            <span>Reports</span>
                                        </a>
                                    </li>
                                </ul>
                                <a class="toggle-hidden-nav-items">

                                </a>
                            </div>
                            <div id="RecentlyViewedView">
                                <h3>Recently Viewed</h3>
                            </div>
                        