<body class="blue"><div id="EmailTemplatesPageView" class="ZurmoDefaultPageView ZurmoPageView PageView"><div id="ZurmoDefaultView"><div class="GridView"><div id="HeaderView"><!-- Start of themes/default/templates/HeaderView.xhtml --><div id="MainLogo" class="zurmo-logo"></div>
<div class="GridView"><div id="HeaderLinksView"><div class="clearfix"><a href="#" id="nav-trigger" title="Toggle Navigation">&rsaquo;</a><div id="corp-logo"><a href="/zurmo/app/index.php/home/default"><img src="/zurmo/app/themes/default/images/Zurmo_logo.png" alt="Zurmo Logo" height="32" width="107" /></a></div><div id="user-toolbar" class="clearfix"><div id="header-game-dashboard-link-wrapper" class="user-menu-item"><a id="header-game-dashboard-link" href="#">∂</a></div><ul id="user-header-menu" class="user-menu-item nav">
<li class="parent last"><a href="javascript:void(0);"><span>super</span></a>
<ul>
<li><a href="/zurmo/app/index.php/users/default/profile"><span>My Profile</span></a></li>
<li><a href="/zurmo/app/index.php/gamification/default/leaderboard"><span>Leaderboard</span></a></li>
<li><a href="/zurmo/app/index.php/emailMessages/default/matchingList"><span>Data Cleanup</span></a></li>
<li class="last"><a href="/zurmo/app/index.php/zurmo/default/logout"><span>Sign out</span></a></li>
</ul>
</li>
</ul><ul id="settings-header-menu" class="user-menu-item nav">
<li class="parent last"><a href="javascript:void(0);"><span>Administration</span></a>
<ul>
<li><a href="/zurmo/app/index.php/configuration"><span>Administration</span></a></li>
<li><a href="/zurmo/app/index.php/designer/default"><span>Designer</span></a></li>
<li><a href="/zurmo/app/index.php/import/default"><span>Import</span></a></li>
<li><a href="/zurmo/app/index.php/users/default"><span>Users</span></a></li>
<li><a href="http://www.zurmo.com/needSupport.php"><span>Need Support?</span></a></li>
<li class="last"><a href="/zurmo/app/index.php/zurmo/default/about"><span>About Zurmo</span></a></li>
</ul>
</li>
</ul></div></div></div><div class="GridView"><div id="GlobalSearchAndShortcutsCreateMenuView"><div id="app-search" class="clearfix"><select class="ignore-style" id="globalSearchScope" multiple="multiple" style="display:none;" size="4" name="globalSearchScope[]">
<option value="All" selected="selected">All</option>
<option value="accounts">Accounts</option>
<option value="contacts">Contacts</option>
<option value="leads">Leads</option>
<option value="opportunities">Opportunities</option>
</select><input class="global-search global-search-hint" onfocus="$(this).removeClass(&quot;global-search-hint&quot;); $(this).val(&quot;&quot;);" onblur="$(this).val(&quot;&quot;)" id="globalSearchInput" type="text" value="Search by name, phone, or e-mail" name="globalSearchInput" /><span class="z-spinner"></span></div><ul id="ShortcutsMenu" class="nav">
<li class="parent last"><a href="javascript:void(0);"><span>Create</span></a>
<ul>
<li><a href="/zurmo/app/index.php/accounts/default/create"><span>Account</span></a></li>
<li><a href="/zurmo/app/index.php/contacts/default/create"><span>Contact</span></a></li>
<li><a href="/zurmo/app/index.php/conversations/default/create"><span>Conversation</span></a></li>
<li><a href="/zurmo/app/index.php/leads/default/create"><span>Lead</span></a></li>
<li><a href="/zurmo/app/index.php/missions/default/create"><span>Mission</span></a></li>
<li><a href="/zurmo/app/index.php/opportunities/default/create"><span>Opportunity</span></a></li>
<li><a href="/zurmo/app/index.php/reports/default/selectType"><span>Report</span></a></li>
<li class="last"><a href="#" id="yt0"><span>Task</span></a></li>
</ul>
</li>
</ul></div></div></div>



<!-- End of themes/default/templates/HeaderView.xhtml --></div><div class="AppContainer clearfix GridView"><div class="AppNavigation clearfix GridView"><div id="MenuView"><ul class="nav">
<li id="home"><a href="/zurmo/app/index.php/home/default"><span></span><em></em><span>Home</span></a></li>
<li id="mashableInbox"><a href="/zurmo/app/index.php/mashableInbox/default"><span></span><em></em><span>Inbox<span class="unread-inbox-count">1</span></span></a></li>
<li id="accounts"><a href="/zurmo/app/index.php/accounts/default"><span></span><em></em><span>Accounts</span></a></li>
<li id="leads"><a href="/zurmo/app/index.php/leads/default"><span></span><em></em><span>Leads</span></a></li>
<li id="contacts"><a href="/zurmo/app/index.php/contacts/default"><span></span><em></em><span>Contacts</span></a></li>
<li id="opportunities"><a href="/zurmo/app/index.php/opportunities/default"><span></span><em></em><span>Opportunities</span></a></li>
<li id="marketing" class="active"><a href="/zurmo/app/index.php/marketing/default/dashboardDetails"><span></span><em></em><span>Marketing</span></a></li>
<li id="projects" class="hidden-nav-item"><a href="/zurmo/app/index.php/projects/default/dashboardDetails"><span></span><em></em><span>Projects</span></a></li>
<li id="products" class="hidden-nav-item"><a href="/zurmo/app/index.php/products/default"><span></span><em></em><span>Products</span></a></li>
<li id="reports" class="hidden-nav-item last"><a href="/zurmo/app/index.php/reports/default"><span></span><em></em><span>Reports</span></a></li>
</ul><a class="toggle-hidden-nav-items"></a></div><div id="RecentlyViewedView"><h3>Recently Viewed</h3><ul class="nav">
<li class="type-EmailTemplatesModule"><a href="/zurmo/app/index.php/emailTemplates/default/details?id=1"><span></span><em></em><span>Discount</span></a></li>
<li class="type-MarketingListsModule last"><a href="/zurmo/app/index.php/marketingLists/default/details?id=1"><span></span><em></em><span>Clients</span></a></li>
</ul></div></div>

<div class="AppContent GridView"><div id="MarketingBreadCrumbView" class="BreadCrumbView"><div class="breadcrumbs">
<a href="/ZurmoBajakan/public/marketing/">Marketing</a> &#47; <a href="/ZurmoBajakan/public/marketing/marketing/template">Templates</a> &#47; <span>Discount</span></div></div><div id="EmailTemplateEditAndDetailsView" class="SecuredEditAndDetailsView EditAndDetailsView DetailsView ModelView ConfigurableMetadataView MetadataView"><div class="details-table"><h1><span class="truncated-title"><span class="ellipsis-content">Discount</span></span></h1><div class="view-toolbar-container toolbar-mbmenu clearfix"><div class="view-toolbar"><ul class="options-menu nav">
<li class="parent last"><a href="javascript:void(0);"><span>Options</span></a>
<ul>
<li id="EditLinkActionElement"><a id="EditLinkActionElement-1-yt2" href="/ZurmoBajakan/public/marketing/marketing/templateedit"><span>Edit</span></a></li>
<li class="last"><a id="EmailTemplateDeleteLinkActionElement-1-yt3" href="/zurmo/app/index.php/emailTemplates/default/delete?id=1"><span>Delete</span></a></li>
</ul>
</li>
</ul></div></div>
<div class="left-column full-width"><div class="panel">
<table class="form-fields">
<colgroup>
<col class="col-0" />
<col class="col-1" />
</colgroup>
<tbody>

<?php  
$koneksi = mysql_connect("localhost", "root", "") or die("Gagal konek ke server.");  
mysql_select_db("zurmo") or die("Gagal membuka database."); 
?> 

<?php 
$query = "select * from emailtemplate";
$hasil = mysql_query($query, $koneksi) or die("Gagal melakukan query.");
$buff = mysql_fetch_array($hasil);
?>

<tr>
<th>Name</th>
<td colspan="1"><?php echo $buff['name']; ?></td>
</tr>

<tr>
<th>Subject</th>
<td colspan="1"><?php echo $buff['subject']; ?></td>
</tr>

<tr>
<th>Attachments</th>
<td colspan="1"></td>
</tr>

</tbody>
</table>
</div>

<div class="email-template-combined-content">
<th></th>
<td colspan="1"><div class="email-template-content">
<div class="tabs-nav"><a class="active-tab" href="#tab1">Text Content</a>
<a href="#tab2">Html Content</a></div> 
<div id="tab1" class="active-tab tab email-template-textContent"><?php echo $buff ['textcontent'];?></div>
<div id="tab2" class=" tab email-template-htmlContent">

<iframe src='/zurmo/app/index.php/emailTemplates/default/getHtmlContent?id=1' class='redactor-iframe' width='100%' height='100%' frameborder='0' seamless></iframe></div></div></td></div></div></div></div></div>
<div id="FlashMessageView"><div id = "FlashMessageBar"></div></div></div><div id="ModalContainerView"><div id="modalContainer"></div></div><div id="ModalGameNotificationContainerView"></div><div id="GameCoinContainerView"></div><div id="FooterView"><a href="http://www.zurmo.com" id="credit-link" class="clearfix"><span>Copyright &#169; Zurmo Inc., 2013. All rights reserved.</span></a><div class="ui-chooser"><a class="icon-mobile" href="/zurmo/app/index.php/zurmo/default/userInterface?userInterface=Mobile"><span>Show Mobile</span></a><a class="icon-desktop active" href="/zurmo/app/index.php/zurmo/default/userInterface?userInterface=Desktop"><span>Show Full</span></a></div></div></div></div></div><script type="text/javascript">
/*<![CDATA[*/

function closeGamificationDashboard(){
                           $('#UserGameDashboardView').remove();
                           $('body').removeClass('gd-dashboard-active');
                           $('#header-game-dashboard-link').html('∂').toggleClass('highlighted');
                       }
jQuery(function($) {

                    jQuery("body").ajaxComplete(
                        function(event, request, options)
                        {
                            if (request.responseText == "sessionTimeout")
                            {
                                $.cookie("sessionTimeoutCookie", 1,
                                        {
                                            expires : 1,
                                            path:  "/"
                                        });
                                window.location.reload(true);
                            }
                        }
                    );
                
$('#go-to-dashboard-link, #close-game-notification-link').click(function(event){
                           event.preventDefault();
                           $('#game-notification').fadeOut(300, function(){
                               $('#game-notification').remove();
                           });
                       });
                       $('.gd-dashboard-active').on('click', function(){
                           if($('#UserGameDashboardView').length){
                               closeGamificationDashboard();
                           }
                           return false;
                       });
$('body').on('click', '#header-game-dashboard-link', function(){jQuery.ajax({'beforeSend':function(){
                    if($("#UserGameDashboardView").length){
                        closeGamificationDashboard();
                        return false;
                    }
                    $("body").addClass("gd-dashboard-active");
                    $("#header-game-dashboard-link").html("‰").toggleClass("highlighted");
                },'success':function(data){$("#FooterView").after(data);},'url':'/zurmo/app/index.php/users/default/gameDashboard?id=1','cache':false});return false;});
  $(".nav li").hover(
    function () {
      if ($(this).hasClass("parent")) {
        $(this).addClass("over");
      }
    },
    function () {
      $(this).removeClass("over");
    }
  );

$("#globalSearchScope").bind("multiselectclick", function(event, ui){
                            if ($("#globalSearchScope").multiselect("widget").find(":checkbox:checked").length == 0)
                            {
                                $("#globalSearchScope").multiselect("widget").find(":checkbox").each(function(){
                                    if (this.value == "All" && !this.checked)
                                    {
                                        this.click();
                                    }
                                });
                            }
                            if (ui.value == "All" && ui.checked)
                            {
                                $("#globalSearchScope").multiselect("widget").find(":checkbox").each(function(){
                                    if (this.value != "All" && this.checked)
                                    {
                                        this.click();
                                    }
                                });
                            }
                            else if (ui.value != "All" && ui.checked)
                            {
                                $("#globalSearchScope").multiselect("widget").find(":checkbox").each(function(){
                                    if (this.value == "All" && this.checked)
                                    {
                                        this.click();
                                    }
                                });
                            }
                        });
                       
$('#globalSearchScope').multiselect({'selectedText':'','noneSelectedText':'','header':false,'position':{'my':'right top','at':'right bottom'}}); $(this).setupCheckboxStyling($('#globalSearchScope').parent())
$("#globalSearchInput").bind("focus", function(event, ui){
                            $("#globalSearchInput").autocomplete("option", "source", "/zurmo/app/index.php/zurmo/default/globalSearchAutoComplete?" + $.param($("#globalSearchScope").serializeArray()));
                        });
                       
jQuery('#globalSearchInput').autocomplete({'select': function(event, ui) {if (ui.item.href.length > 0){window.location = ui.item.href;} return false;},'search': function(event, ui) { $(this).makeOrRemoveTogglableSpinner(true, "#app-search") },'open': function(event, ui) { $(this).makeOrRemoveTogglableSpinner(false, "#app-search") },'position':{'my':'right top','at':'right bottom'},'source':'/zurmo/app/index.php/zurmo/default/globalSearchAutoComplete'});
 $("#globalSearchInput").data( "autocomplete" )._renderItem = function( ul, item ) {
                            return $( "<li></li>" ).data( "item.autocomplete", item )
                                    .append( "<a><span class=" + item.iconClass + "></span><span>" + item.label + "</span></a>" )
                                    .appendTo( ul );
                        };
$('body').on('click', '#yt0', function(){jQuery.ajax({'beforeSend':function(){
                jQuery('#modalContainer').html('');
                $(this).makeLargeLoadingSpinner(true, '#modalContainer');
                window.scrollTo(0, 0);
                jQuery('#modalContainer').dialog({
                    'title' : 'Create Task',
                    'autoOpen' : true,
                    'modal' : true,
                    'position' : 'center top+25',
                    'dialogClass' : 'task-dialog',
                    'height' : 'auto',
                    'open': function( event, ui )  { jQuery('#modalContainer').parent().addClass('openingModal'); },
                    'close': function( event, ui ) { jQuery('#modalContainer').parent().removeClass('openingModal');
                                                     $('#modalContainer').dialog('destroy');
                                                     
                                                     }
                });
                return true;
            },'url':'/zurmo/app/index.php/tasks/default/modalCreate?modalId=modalContainer','cache':false,'success':function(html){jQuery("#modalContainer").html(html)}});return false;});

                    $(function() {
                        $('.truncated-title').ThreeDots({ max_rows:1 });
                    });
jQuery('body').on('click','#EmailTemplateDeleteLinkActionElement-1-yt3',function(){return confirm('Are you sure you want to delete this email template?');});

                        $('.tabs-nav a:not(.simple-link)').click( function()
                        {
                            //the menu items
                            $('.active-tab', $(this).parent()).removeClass('active-tab');
                            $(this).addClass('active-tab');
                            //the sections
                            var _old = $('.tab.active-tab'); //maybe add context here for tab-container
                            _old.fadeToggle();
                            var _new = $( $(this).attr('href') );
                            _new.fadeToggle(150, 'linear', function()
                            {
                                    _old.removeClass('active-tab');
                                    _new.addClass('active-tab');
                            });
                            return false;
                        });
                    
});
/*]]>*/
</script>
</body>