<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Opportunity\Module'                        => __DIR__ . '/Module.php',
    'Opportunity\Controller\OpportunityController' => __DIR__ . '/src/Opportunity/Controller/OpportunityController.php',
    'OpportunityTest\Framework\TestCase'        => __DIR__ . '/tests/Opportunity/Framework/TestCase.php',
    'OpportunityTest\SampleTest'                => __DIR__ . '/tests/Opportunity/SampleTest.php',
);
