<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Inbox\Module'                        => __DIR__ . '/Module.php',
    'Inbox\Controller\InboxController' => __DIR__ . '/src/Inbox/Controller/InboxController.php',
    'InboxTest\Framework\TestCase'        => __DIR__ . '/tests/Inbox/Framework/TestCase.php',
    'InboxTest\SampleTest'                => __DIR__ . '/tests/Inbox/SampleTest.php',
);
